version: 2
updates:
  # Go modules
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      minor-patch:
        update-types: ["minor", "patch"]
    reviewers:
      - mwaldheim

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        update-types: ["minor", "patch"]
    reviewers:
      - mwaldheim
