# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The go-semrel Authors

name: REUSE

on:
  pull_request:
    branches: ["main"]

permissions: read-all

jobs:
  reuse:
    name: REUSE Compliance
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: REUSE lint
        uses: fsfe/reuse-action@ef1dfe28dda4d13f5d580f0444eb27dda9746e9b # v5
