# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The go-semrel Authors

name: REUSE

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  reuse:
    name: REUSE Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: REUSE lint
        uses: fsfe/reuse-action@v5
